# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66c6e0a1960328a2c52f88fac25578b46237a2dfd49f4725fd0ab9a43b58b1c2c3fc66a38ae36a8117f154e6dd1f8169de07b87e979a1006704278ff31aab935

test:
  secret_key_base: 4d45b6962c919b08a044959bd825356784052e83ffc694eac46450c678456adf1221271940dda242de2bc4ce40ea83f02f85516ff3c830939ec62dd75779d722

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
